import { LLMModel } from '@prisma/client';
type LLMModelOmitType = Omit<LLMModel, 'id' | 'created_at' | 'updated_at'>;

export const PRE_CONFIGURED_LLM_MODEL: LLMModelOmitType[] = [
  {
    name: 'Qwen2.5-Coder 14B Basic',
    modelName: 'qwen2.5-coder:14b',
    version: 'latest',
    description:
      'Qwen2.5-Coder 14B with basic settings for balanced code generation and general-purpose coding assistance. Provides a good balance between creativity and reliability.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.1,
    presence_penaltyMax: 0.1,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.1,
    frequency_penaltyMax: 0.1,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: ['\n```', '\n\n'],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful coding assistant. Provide clear and concise code examples and explanations. Prioritize correctness and readability.',
  },
  {
    name: 'Qwen2.5-Coder 14B Deterministic',
    modelName: 'qwen2.5-coder:14b',
    version: 'latest',
    description:
      'Qwen2.5-Coder 14B configured for highly predictable and consistent code generation. Emphasizes reliability and adherence to established coding patterns. Ideal for situations where consistency and reproducibility are paramount.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 5,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 1024,
    max_tokensDefault: 256,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: -0.3,
    presence_penaltyDefault: -0.4,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: -0.3,
    frequency_penaltyDefault: -0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.05,
    repeat_penaltyDefault: 1.02,
    stop_sequences: ['\n```', '\n\n'],
    usageCount: 0,
    defaultPrompt:
      'You are a highly reliable and deterministic coding assistant. Focus on generating the most predictable and consistent code possible. Always prioritize well-established coding patterns and avoid any ambiguity or experimentation. Ensure the code is highly readable and easily understood. Repeatability is paramount.',
  },
  {
    name: 'Qwen2.5-Coder 14B Creative',
    modelName: 'qwen2.5-coder:14b',
    version: 'latest',
    description:
      'Qwen2.5-Coder 14B with a creative configuration designed to generate novel and imaginative code solutions, even when faced with ambiguous or complex prompts. Emphasizes exploration and unconventional approaches.',
    temperatureMin: 0.7,
    temperatureMax: 1.2,
    temperatureDefault: 0.9,
    top_pMin: 0.6,
    top_pMax: 0.9,
    top_pDefault: 0.75,
    top_kMin: 10,
    top_kMax: 30,
    top_kDefault: 15,
    max_tokensMin: 1,
    max_tokensMax: 4096,
    max_tokensDefault: 1024,
    presence_penaltyMin: -0.2,
    presence_penaltyMax: 0.8,
    presence_penaltyDefault: 0.3,
    frequency_penaltyMin: -0.2,
    frequency_penaltyMax: 0.8,
    frequency_penaltyDefault: 0.3,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.2,
    repeat_penaltyDefault: 1.15,
    stop_sequences: ['\n```', '\n\n', '<|file_separator|>'],
    usageCount: 0,
    defaultPrompt:
      'You are an exceptionally creative and resourceful AI coding assistant. When presented with a coding problem, think outside the box and explore unconventional solutions. Embrace ambiguity and strive for originality. Prioritize creative problem-solving over strict adherence to existing patterns. Consider edge cases and explore novel approaches. Aim for surprising and delightful code.',
  },

  {
    name: 'DeepSeek-R1 8B Basic',
    modelName: 'deepseek-r1:8b',
    version: 'latest',
    description:
      'DeepSeek-R1 8B with basic settings for balanced and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful and informative assistant. Provide clear and concise answers to the best of your ability.',
  },
  {
    name: 'DeepSeek-R1 8B Deterministic',
    modelName: 'deepseek-r1:8b',
    version: 'latest',
    description:
      'DeepSeek-R1 8B with deterministic settings for predictable and consistent responses.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise and factual assistant. Provide direct and concise answers, avoiding ambiguity and creative embellishments.',
  },
  {
    name: 'DeepSeek-R1 8B Creative',
    modelName: 'deepseek-r1:8b',
    version: 'latest',
    description:
      'DeepSeek-R1 8B with creative settings for imaginative and engaging responses.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative and imaginative assistant.  Craft elaborate and engaging responses, adding creative details and insights. Inject personality and flair into your answers.',
  },

  {
    name: 'Llama3.2-Vision Basic',
    modelName: 'llama3.2-vision:latest',
    version: 'latest',
    description:
      'Llama3.2-Vision with basic settings for image understanding and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful assistant for image understanding. Describe the image clearly and concisely.',
  },
  {
    name: 'Llama3.2-Vision Deterministic',
    modelName: 'llama3.2-vision:latest',
    version: 'latest',
    description:
      'Llama3.2-Vision with Deterministic settings for image understanding and precise responses.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise assistant for image understanding. Describe the image clearly with accurate details.',
  },
  {
    name: 'Llama3.2-Vision Creative',
    modelName: 'llama3.2-vision:latest',
    version: 'latest',
    description:
      'Llama3.2-Vision with Creative settings for image understanding and imaginative responses.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative assistant for image understanding. Describe the image imaginatively with creative details.',
  },

  {
    name: 'Llama3.2 Basic',
    modelName: 'llama3.2:latest',
    version: 'latest',
    description:
      'Llama3.2 with basic settings for balanced and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful and informative assistant. Provide clear and concise answers to the best of your ability.',
  },
  {
    name: 'Llama3.2 Deterministic',
    modelName: 'llama3.2:latest',
    version: 'latest',
    description:
      'Llama3.2 with deterministic settings for predictable and consistent responses.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise and factual assistant. Provide direct and concise answers, avoiding ambiguity and creative embellishments.',
  },
  {
    name: 'Llama3.2 Creative',
    modelName: 'llama3.2:latest',
    version: 'latest',
    description:
      'Llama3.2 with creative settings for imaginative and engaging responses.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative and imaginative assistant.  Craft elaborate and engaging responses, adding creative details and insights. Inject personality and flair into your answers.',
  },
];
