import { LLMModel } from '@prisma/client';
type LLMModelOmitType = Omit<LLMModel, 'id' | 'created_at' | 'updated_at'>;

export const PRE_CONFIGURED_LLM_MODEL: LLMModelOmitType[] = [
  {
    name: 'StarCoder2-3B-Basic',
    modelName: 'starcoder2:3b',
    version: 'latest',
    description: 'StarCoder2 3B with default settings.',
    temperatureMin: 0,
    temperatureMax: 1,
    temperatureDefault: 0.7,
    top_pMin: 0,
    top_pMax: 1,
    top_pDefault: 0.9,
    top_kMin: 0,
    top_kMax: 100,
    top_kDefault: 0,
    max_tokensMin: 1,
    max_tokensMax: 4096,
    max_tokensDefault: 256,
    presence_penaltyMin: -2,
    presence_penaltyMax: 2,
    presence_penaltyDefault: 0,
    frequency_penaltyMin: -2,
    frequency_penaltyMax: 2,
    frequency_penaltyDefault: 0,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 2,
    repeat_penaltyDefault: 1,
    stop_sequences: ['<|file_separator|>', '<|end_of_turn|>'],
    usageCount: 0,
    defaultPrompt:
      "You are a helpful coding assistant. Provide clear, concise, and functional code snippets. Explain the code's purpose and usage.",
  },
  {
    name: 'StarCoder2-3B-Deterministic',
    modelName: 'starcoder2:3b',
    version: 'latest',
    description: 'StarCoder2 3B for more deterministic code generation.',
    temperatureMin: 0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 0,
    top_kMax: 5,
    top_kDefault: 3,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1,
    presence_penaltyMax: 1,
    presence_penaltyDefault: 0,
    frequency_penaltyMin: -1,
    frequency_penaltyMax: 1,
    frequency_penaltyDefault: 0,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 1.2,
    repeat_penaltyDefault: 1.1,
    stop_sequences: ['<|file_separator|>', '<|end_of_turn|>'],
    usageCount: 0,
    defaultPrompt:
      'You are a precise coding assistant. Provide only the necessary functional code without any extra explanations or commentary.',
  },
  {
    name: 'StarCoder2-3B-Creative',
    modelName: 'starcoder2:3b',
    version: 'latest',
    description: 'StarCoder2 3B for more creative and varied code generation.',
    temperatureMin: 0.7,
    temperatureMax: 1,
    temperatureDefault: 0.8,
    top_pMin: 0.7,
    top_pMax: 1,
    top_pDefault: 0.95,
    top_kMin: 50,
    top_kMax: 100,
    top_kDefault: 75,
    max_tokensMin: 1,
    max_tokensMax: 4096,
    max_tokensDefault: 1024,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: ['<|file_separator|>', '<|end_of_turn|>'],
    usageCount: 0,
    defaultPrompt:
      'You are an imaginative coding assistant. Generate novel and diverse code solutions, even if unconventional. Always explain your creative choices.',
  },
  {
    name: 'Gemma-2B-Basic',
    modelName: 'gemma:2b',
    version: 'latest',
    description: 'Gemma 2B with default settings.',
    temperatureMin: 0,
    temperatureMax: 1,
    temperatureDefault: 0.7,
    top_pMin: 0,
    top_pMax: 1,
    top_pDefault: 0.9,
    top_kMin: 0,
    top_kMax: 100,
    top_kDefault: 0,
    max_tokensMin: 1,
    max_tokensMax: 4096,
    max_tokensDefault: 256,
    presence_penaltyMin: -2,
    presence_penaltyMax: 2,
    presence_penaltyDefault: 0,
    frequency_penaltyMin: -2,
    frequency_penaltyMax: 2,
    frequency_penaltyDefault: 0,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 2,
    repeat_penaltyDefault: 1,
    stop_sequences: ['<|file_separator|>', '<|end_of_turn|>'],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful assistant. Provide informative and concise responses to user questions.',
  },
  {
    name: 'Gemma-2B-CreativeText',
    modelName: 'gemma:2b',
    version: 'latest',
    description: 'Gemma 2B for creative text generation.',
    temperatureMin: 0.6,
    temperatureMax: 1,
    temperatureDefault: 0.8,
    top_pMin: 0.6,
    top_pMax: 1,
    top_pDefault: 0.95,
    top_kMin: 20,
    top_kMax: 100,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: ['<|file_separator|>', '<|end_of_turn|>'],
    usageCount: 0,
    defaultPrompt:
      'You are a creative writer. Generate imaginative and engaging stories, poems, or articles. Use vivid language and compelling narratives.',
  },
  {
    name: 'Gemma-2B-QuestionAnswering',
    modelName: 'gemma:2b',
    version: 'latest',
    description: 'Gemma 2B for focused question answering.',
    temperatureMin: 0,
    temperatureMax: 0.5,
    temperatureDefault: 0.3,
    top_pMin: 0,
    top_pMax: 0.5,
    top_pDefault: 0.4,
    top_kMin: 5,
    top_kMax: 50,
    top_kDefault: 20,
    max_tokensMin: 1,
    max_tokensMax: 1024,
    max_tokensDefault: 256,
    presence_penaltyMin: -1,
    presence_penaltyMax: 0,
    presence_penaltyDefault: -0.5,
    frequency_penaltyMin: -1,
    frequency_penaltyMax: 0,
    frequency_penaltyDefault: -0.5,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.1,
    stop_sequences: ['<|file_separator|>', '<|end_of_turn|>'],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful question answering assistant. Provide accurate and concise answers to user questions. Focus on factual information and avoid speculation.',
  },
  {
    name: 'Llama3-Vision-Basic',
    modelName: 'llama3.2-vision:latest',
    version: 'latest',
    description: 'Llama 3.2 Vision with default settings.',
    temperatureMin: 0,
    temperatureMax: 1,
    temperatureDefault: 0.7,
    top_pMin: 0,
    top_pMax: 1,
    top_pDefault: 0.9,
    top_kMin: 0,
    top_kMax: 100,
    top_kDefault: 0,
    max_tokensMin: 1,
    max_tokensMax: 4096,
    max_tokensDefault: 256,
    presence_penaltyMin: -2,
    presence_penaltyMax: 2,
    presence_penaltyDefault: 0,
    frequency_penaltyMin: -2,
    frequency_penaltyMax: 2,
    frequency_penaltyDefault: 0,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 2,
    repeat_penaltyDefault: 1,
    stop_sequences: ['<|file_separator|>', '<|end_of_turn|>'],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful multimodal assistant. Describe images and answer questions accurately and concisely.',
  },
  {
    name: 'Llama3-Vision-Deterministic',
    modelName: 'llama3.2-vision:latest',
    version: 'latest',
    description: 'Llama 3.2 Vision for more deterministic output.',
    temperatureMin: 0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 0,
    top_kMax: 5,
    top_kDefault: 3,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1,
    presence_penaltyMax: 1,
    presence_penaltyDefault: 0,
    frequency_penaltyMin: -1,
    frequency_penaltyMax: 1,
    frequency_penaltyDefault: 0,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 1.2,
    repeat_penaltyDefault: 1.1,
    stop_sequences: ['<|file_separator|>', '<|end_of_turn|>'],
    usageCount: 0,
    defaultPrompt:
      'You are an analytical multimodal assistant. Provide factual descriptions and answers without creative embellishments.',
  },
  {
    name: 'Llama3-Vision-Creative',
    modelName: 'llama3.2-vision:latest',
    version: 'latest',
    description: 'Llama 3.2 Vision for more creative output.',
    temperatureMin: 0.7,
    temperatureMax: 1,
    temperatureDefault: 0.8,
    top_pMin: 0.7,
    top_pMax: 1,
    top_pDefault: 0.95,
    top_kMin: 50,
    top_kMax: 100,
    top_kDefault: 75,
    max_tokensMin: 1,
    max_tokensMax: 4096,
    max_tokensDefault: 1024,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: ['<|file_separator|>', '<|end_of_turn|>'],
    usageCount: 0,
    defaultPrompt:
      'You are an artistic multimodal assistant. Generate creative and expressive descriptions and responses.',
  },
  {
    name: 'Qwen2 0.5B Basic',
    modelName: 'qwen2:0.5b',
    version: 'latest',
    description: 'Qwen2 0.5B with basic settings.',
    temperatureMin: 0,
    temperatureMax: 1,
    temperatureDefault: 0.7,
    top_pMin: 0,
    top_pMax: 1,
    top_pDefault: 0.9,
    top_kMin: 0,
    top_kMax: 100,
    top_kDefault: 0,
    max_tokensMin: 1,
    max_tokensMax: 4096,
    max_tokensDefault: 256,
    presence_penaltyMin: -2,
    presence_penaltyMax: 2,
    presence_penaltyDefault: 0,
    frequency_penaltyMin: -2,
    frequency_penaltyMax: 2,
    frequency_penaltyDefault: 0,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 2,
    repeat_penaltyDefault: 1,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful assistant. Provide informative and concise responses to user questions.',
  },
  {
    name: 'Qwen2 0.5B Deterministic',
    modelName: 'qwen2:0.5b',
    version: 'latest',
    description:
      'Qwen2 0.5B with deterministic settings for consistent results.',
    temperatureMin: 0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 0,
    top_kMax: 10,
    top_kDefault: 5,
    max_tokensMin: 1,
    max_tokensMax: 4096,
    max_tokensDefault: 256,
    presence_penaltyMin: -2,
    presence_penaltyMax: 2,
    presence_penaltyDefault: 0,
    frequency_penaltyMin: -2,
    frequency_penaltyMax: 2,
    frequency_penaltyDefault: 0,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 2,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise assistant. Provide brief, direct answers based on factual knowledge.',
  },
  {
    name: 'Qwen2 0.5B Creative',
    modelName: 'qwen2:0.5b',
    version: 'latest',
    description:
      'Qwen2 0.5B with creative settings for more varied and imaginative responses.',
    temperatureMin: 0.7,
    temperatureMax: 1,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1,
    top_pDefault: 0.9,
    top_kMin: 50,
    top_kMax: 100,
    top_kDefault: 75,
    max_tokensMin: 1,
    max_tokensMax: 4096,
    max_tokensDefault: 256,
    presence_penaltyMin: -2,
    presence_penaltyMax: 2,
    presence_penaltyDefault: 0.2,
    frequency_penaltyMin: -2,
    frequency_penaltyMax: 2,
    frequency_penaltyDefault: 0.2,
    repeat_penaltyMin: 1,
    repeat_penaltyMax: 2,
    repeat_penaltyDefault: 1.1,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are an imaginative assistant. Craft elaborate and engaging responses, adding creative details and insights.',
  },
];
