import { LLMModel } from '@prisma/client';
type LLMModelOmitType = Omit<LLMModel, 'id' | 'created_at' | 'updated_at'>;

export const PRE_CONFIGURED_LLM_MODEL: LLMModelOmitType[] = [
  {
    name: 'CodeLlama 7B Basic',
    modelName: 'codellama:7b',
    version: 'latest',
    description:
      'CodeLlama 7B with basic settings for balanced code generation and general-purpose coding assistance.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: ['\n```', '\n\n'],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful coding assistant.  Provide clear and concise code examples and explanations.  Prioritize correctness and readability.',
  },
  {
    name: 'CodeLlama 7B Deterministic',
    modelName: 'codellama:7b',
    version: 'latest',
    description:
      'CodeLlama 7B with deterministic settings for predictable and consistent code generation.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: ['\n```', '\n\n'],
    usageCount: 0,
    defaultPrompt:
      'You are a precise code generation assistant. Provide direct and consistent code examples with minimal variation. Focus on generating the exact code requested.',
  },
  {
    name: 'CodeLlama 7B Creative',
    modelName: 'codellama:7b',
    version: 'latest',
    description:
      'CodeLlama 7B with creative settings for exploring code generation ideas and suggestions.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: ['\n```', '\n\n'],
    usageCount: 0,
    defaultPrompt:
      'You are a creative coding assistant. Suggest unconventional and innovative code solutions and approaches. Explore different ways to solve the problem.',
  },
  {
    name: 'DeepSeek-R1.5B Basic',
    modelName: 'deepseek-r1:1.5b',
    version: 'latest',
    description:
      'DeepSeek-R1.5B with basic settings for balanced and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful and informative assistant. Provide clear and concise answers to the best of your ability.',
  },
  {
    name: 'DeepSeek-R1.5B Deterministic',
    modelName: 'deepseek-r1:1.5b',
    version: 'latest',
    description:
      'DeepSeek-R1.5B with deterministic settings for predictable and consistent responses.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise and factual assistant. Provide direct and concise answers, avoiding ambiguity and creative embellishments.',
  },
  {
    name: 'DeepSeek-R1.5B Creative',
    modelName: 'deepseek-r1:1.5b',
    version: 'latest',
    description:
      'DeepSeek-R1.5B with creative settings for imaginative and engaging responses.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative and imaginative assistant.  Craft elaborate and engaging responses, adding creative details and insights. Inject personality and flair into your answers.',
  },
  {
    name: 'DeepSeek-R1 8B Basic',
    modelName: 'deepseek-r1:8b',
    version: 'latest',
    description:
      'DeepSeek-R1 8B with basic settings for balanced and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful and informative assistant. Provide clear and concise answers to the best of your ability.',
  },
  {
    name: 'DeepSeek-R1 8B Deterministic',
    modelName: 'deepseek-r1:8b',
    version: 'latest',
    description:
      'DeepSeek-R1 8B with deterministic settings for predictable and consistent responses.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise and factual assistant. Provide direct and concise answers, avoiding ambiguity and creative embellishments.',
  },
  {
    name: 'DeepSeek-R1 8B Creative',
    modelName: 'deepseek-r1:8b',
    version: 'latest',
    description:
      'DeepSeek-R1 8B with creative settings for imaginative and engaging responses.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative and imaginative assistant.  Craft elaborate and engaging responses, adding creative details and insights. Inject personality and flair into your answers.',
  },
  {
    name: 'Qwen2 0.5B Basic',
    modelName: 'qwen2:0.5b',
    version: 'latest',
    description:
      'Qwen2 0.5B with basic settings for balanced and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful and informative assistant. Provide clear and concise answers to the best of your ability.',
  },
  {
    name: 'Qwen2 0.5B Deterministic',
    modelName: 'qwen2:0.5b',
    version: 'latest',
    description:
      'Qwen2 0.5B with deterministic settings for predictable and consistent responses.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise and factual assistant. Provide direct and concise answers, avoiding ambiguity and creative embellishments.',
  },
  {
    name: 'Qwen2 0.5B Creative',
    modelName: 'qwen2:0.5b',
    version: 'latest',
    description:
      'Qwen2 0.5B with creative settings for imaginative and engaging responses.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative and imaginative assistant.  Craft elaborate and engaging responses, adding creative details and insights. Inject personality and flair into your answers.',
  },
  {
    name: 'StarCoder2 3B Basic',
    modelName: 'starcoder2:3b',
    version: 'latest',
    description:
      'StarCoder2 3B with basic settings for balanced code generation and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful assistant for coding tasks. Provide clear and concise code examples and explanations.',
  },
  {
    name: 'StarCoder2 3B Deterministic',
    modelName: 'starcoder2:3b',
    version: 'latest',
    description:
      'StarCoder2 3B with deterministic settings for predictable code generation.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise code generation assistant. Provide direct and consistent code examples with minimal variation.',
  },
  {
    name: 'StarCoder2 3B Creative',
    modelName: 'starcoder2:3b',
    version: 'latest',
    description:
      'StarCoder2 3B with creative settings for exploring code generation ideas and suggestions.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative coding assistant. Suggest unconventional and innovative code solutions and approaches.',
  },
  {
    name: 'Llama3.2-Vision Basic',
    modelName: 'llama3.2-vision:latest',
    version: 'latest',
    description:
      'Llama3.2-Vision with basic settings for image understanding and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful assistant for image understanding. Describe the image clearly and concisely.',
  },
  {
    name: 'Llama3.2-Vision Deterministic',
    modelName: 'llama3.2-vision:latest',
    version: 'latest',
    description:
      'Llama3.2-Vision with Deterministic settings for image understanding and precise responses.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise assistant for image understanding. Describe the image clearly with accurate details.',
  },
  {
    name: 'Llama3.2-Vision Creative',
    modelName: 'llama3.2-vision:latest',
    version: 'latest',
    description:
      'Llama3.2-Vision with Creative settings for image understanding and imaginative responses.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative assistant for image understanding. Describe the image imaginatively with creative details.',
  },
  {
    name: 'Gemma 2B Basic',
    modelName: 'gemma:2b',
    version: 'latest',
    description:
      'Gemma 2B with basic settings for balanced and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful and informative assistant. Provide clear and concise answers to the best of your ability.',
  },
  {
    name: 'Gemma 2B Deterministic',
    modelName: 'gemma:2b',
    version: 'latest',
    description:
      'Gemma 2B with deterministic settings for predictable and consistent responses.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise and factual assistant. Provide direct and concise answers, avoiding ambiguity and creative embellishments.',
  },
  {
    name: 'Gemma 2B Creative',
    modelName: 'gemma:2b',
    version: 'latest',
    description:
      'Gemma 2B with creative settings for imaginative and engaging responses.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative and imaginative assistant.  Craft elaborate and engaging responses, adding creative details and insights. Inject personality and flair into your answers.',
  },
  {
    name: 'Qwen2 1.5B Basic',
    modelName: 'qwen2:1.5b',
    version: 'latest',
    description:
      'Qwen2 1.5B with basic settings for balanced and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful and informative assistant. Provide clear and concise answers to the best of your ability.',
  },
  {
    name: 'Qwen2 1.5B Deterministic',
    modelName: 'qwen2:1.5b',
    version: 'latest',
    description:
      'Qwen2 1.5B with deterministic settings for predictable and consistent responses.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise and factual assistant. Provide direct and concise answers, avoiding ambiguity and creative embellishments.',
  },
  {
    name: 'Qwen2 1.5B Creative',
    modelName: 'qwen2:1.5b',
    version: 'latest',
    description:
      'Qwen2 1.5B with creative settings for imaginative and engaging responses.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative and imaginative assistant.  Craft elaborate and engaging responses, adding creative details and insights. Inject personality and flair into your answers.',
  },
  {
    name: 'Llama3.2 Basic',
    modelName: 'llama3.2:latest',
    version: 'latest',
    description:
      'Llama3.2 with basic settings for balanced and general-purpose responses.',
    temperatureMin: 0.4,
    temperatureMax: 0.6,
    temperatureDefault: 0.5,
    top_pMin: 0.4,
    top_pMax: 0.6,
    top_pDefault: 0.5,
    top_kMin: 20,
    top_kMax: 40,
    top_kDefault: 30,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -0.5,
    presence_penaltyMax: 0.5,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -0.5,
    frequency_penaltyMax: 0.5,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.1,
    repeat_penaltyDefault: 1.05,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a helpful and informative assistant. Provide clear and concise answers to the best of your ability.',
  },
  {
    name: 'Llama3.2 Deterministic',
    modelName: 'llama3.2:latest',
    version: 'latest',
    description:
      'Llama3.2 with deterministic settings for predictable and consistent responses.',
    temperatureMin: 0.0,
    temperatureMax: 0.2,
    temperatureDefault: 0.1,
    top_pMin: 0.0,
    top_pMax: 0.2,
    top_pDefault: 0.1,
    top_kMin: 1,
    top_kMax: 10,
    top_kDefault: 1,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.0,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.0,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.0,
    repeat_penaltyDefault: 1.0,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a precise and factual assistant. Provide direct and concise answers, avoiding ambiguity and creative embellishments.',
  },
  {
    name: 'Llama3.2 Creative',
    modelName: 'llama3.2:latest',
    version: 'latest',
    description:
      'Llama3.2 with creative settings for imaginative and engaging responses.',
    temperatureMin: 0.7,
    temperatureMax: 1.0,
    temperatureDefault: 0.9,
    top_pMin: 0.7,
    top_pMax: 1.0,
    top_pDefault: 0.9,
    top_kMin: 40,
    top_kMax: 80,
    top_kDefault: 50,
    max_tokensMin: 1,
    max_tokensMax: 2048,
    max_tokensDefault: 512,
    presence_penaltyMin: -1.0,
    presence_penaltyMax: 1.0,
    presence_penaltyDefault: 0.4,
    frequency_penaltyMin: -1.0,
    frequency_penaltyMax: 1.0,
    frequency_penaltyDefault: 0.4,
    repeat_penaltyMin: 1.0,
    repeat_penaltyMax: 1.5,
    repeat_penaltyDefault: 1.2,
    stop_sequences: [],
    usageCount: 0,
    defaultPrompt:
      'You are a creative and imaginative assistant.  Craft elaborate and engaging responses, adding creative details and insights. Inject personality and flair into your answers.',
  },
];
